version: "3.7"

services:
  apache:
    image: aprendendolinux/apache
    restart: always
    container_name: apache
    volumes:
      - apache:/var/www/html
    ports:
      - "80:80"
volumes:
  apache: